### PR TITLE
Fix the implementation for the multi payload

### LINKED ISSUE #409: Multiple payload still broke
https://github.com/1c3t3a/rust-socketio/pull/392/files#diff-dd5d6ff18628a21723847133d6e54ab531454037b62be81d2c42109d333aeab9L481

https://github.com/1c3t3a/rust-socketio/pull/392/files#diff-58d0f04893e736959d245d946a723085fd60d5b9fd211a5e3eac8c2a4b8821f6L315

https://github.com/1c3t3a/rust-socketio/pull/392/files#diff-58d0f04893e736959d245d946a723085fd60d5b9fd211a5e3eac8c2a4b8821f6L347

### PR DESCRIPTION
**Pull request by shenjackyuanjie**
tested on true workflow

a part of #385

and will fix #409

### CODE REVIEW

**Comment by shenjackyuanjie** [comment]
@1c3t3a please take a few minute to view this PR

File: socketio/src/client/raw_client.rs [hunk 1]
```diff
@@ -288,8 +288,29 @@ impl RawClient {
...
+                            );
+                        }
+                        if let Some(ref attachments) = socket_packet.attachments {
+                            if let Some(payload) = attachments.first() {
+                                ack.callback.deref_mut()(
+                                    Payload::Binary(payload.to_owned()),
+                                    self.clone(),
+                                );
+                            }
+                        }
```
Comment (1c3t3a) [inline socketio/src/client/raw_client.rs:311]: Your are calling the callbacks three times in a row, is that expected behaviour? Wouldn't it be expected to call it once, but with all data at once?

File: socketio/src/client/raw_client.rs [hunk 2]
```diff
@@ -288,8 +288,29 @@ impl RawClient {
...
+                    } else {
+                        // Do something with timed out acks?
```
Comment (1c3t3a) [inline socketio/src/client/raw_client.rs:313]: Definitely! Remove  the ack for sure, also call the error callback? Or maybe just ignore. Would be good to see what the JS implementation does.

File: socketio/src/client/raw_client.rs (hunk 1 above)
Comment (shenjackyuanjie) [reply socketio/src/client/raw_client.rs:311]: I'm not sure about this changes, I copy them from the OLD PR
maybe just remove them?

Comment (1c3t3a) [reply socketio/src/client/raw_client.rs:311]: Well, you are proposing a change here, so I would expect you could take a look at this to make it work?

https://github.com/socketio/socket.io-client should have it somewhere in its JS code :)

**Comment by 1c3t3a** [comment]
Hey @shenjackyuanjie, I appreciate your interest in this repository and project. I see you identified a few things that we can improve upon and a few features we can implement, which is great!

In order to keep the code maintainable and healthy, I highly value small and easily reviewable chunks of code (reading PRs). Also every new code must come with sufficient testing and should be of reasonable quality.

For the changes you do to the project, I noticed you don't necessarily follow that approach. For example this PR contains a bunch of different feature implementations. With this it is not possible for me to review that code and for you it reduces the chance of ever merging the feature.

To move forward I advise you to create small increments of high quality code (you know what each line of code you submit does and why it needs to be there) for me to review. Also please break things down in smaller features and add sufficient tests for everything, otherwise I will reject patches.

**Comment by shenjackyuanjie** [comment]
ah, I'm sorry with the last commit, I forget it's still on this PR
I will reset the branch back

File: socketio/src/client/raw_client.rs (hunk 1 above)
Comment (shenjackyuanjie) [reply socketio/src/client/raw_client.rs]: https://github.com/socketio/socket.io-client/blob/main/lib/socket.ts#L467-L495
so, yea, just nothing to do, remove the ack id and ignore it

File: socketio/src/asynchronous/client/client.rs [hunk 3]
```diff
@@ -461,29 +461,28 @@ impl Client {
...
-                (
-                    Event::Message,
-                    contents.first().ok_or(Error::IncompletePacket())?,
-                )
+            let (event, payloads) = match contents.len() {
+                0 => return Err(Error::IncompletePacket()),
+                1 => {
+                    (
+                        Event::Message,
+                        contents.as_slice(), // safe to unwrap, checked above
```
Comment (1c3t3a) [inline socketio/src/asynchronous/client/client.rs:474]: You don't unwrap here, why the comment?

File: socketio/src/asynchronous/client/client.rs [hunk 4]
```diff
@@ -461,29 +461,28 @@ impl Client {
...
+                    )
+                }
+                _ => match contents.first() {
+                    // get rest of data if first is a event
```
Comment (1c3t3a) [inline socketio/src/asynchronous/client/client.rs:478]: nit: "Get rest of data if first is an event."

**Review by 1c3t3a — CHANGES_REQUESTED** [review]
Could you please add a test or further explain what exactly that code enables? :)

File: socketio/src/asynchronous/client/client.rs (hunk 3 above)
Comment (shenjackyuanjie) [reply socketio/src/asynchronous/client/client.rs:474]: that's some left over

**Comment by shenjackyuanjie** [comment]
> Could you please add a test or further explain what exactly that code enables? :)

the first is just a leftover comment, there aren't any unwrap

I add more comment for the second one

**Comment by shenjackyuanjie** [comment]
@1c3t3a please have a check of the code and the comment

**Comment by 1c3t3a** [comment]
Can you please add a test for the behavior you're changing here? :)

**Comment by shenjackyuanjie** [comment]
code coverage faild ……
weird, but the test do passed

File: engineio/src/packet.rs [hunk 5]
```diff
@@ -1,4 +1,3 @@
-extern crate base64;
```
Comment (1c3t3a) [inline engineio/src/packet.rs:1]: Why is this needed?

File: socketio/src/client/raw_client.rs [hunk 6]
```diff
@@ -288,13 +288,16 @@ impl RawClient {
...
                     }
                 }
-            } else {
-                // Do something with timed out acks?
             }
+            // nope, just ignore it, the official implment just remove the ack id when timeout
+            // https://github.com/socketio/socket.io-client/blob/main/lib/socket.ts#L467-L495
+            // } else {
+            //     // Do something with timed out acks?
+            // }
```
Comment (1c3t3a) [inline socketio/src/client/raw_client.rs:300]: Why is this code here?

File: socketio/src/client/raw_client.rs [hunk 7]
```diff
@@ -327,29 +330,28 @@ impl RawClient {
...
-                (
-                    Event::Message,
-                    contents.first().ok_or(Error::IncompletePacket())?,
-                )
+            let (event, payloads) = match contents.len() {
+                0 => return Err(Error::IncompletePacket()),
+                1 => {
+                    (
+                        Event::Message,
+                        contents.as_slice(), // safe to unwrap, checked above
```
Comment (1c3t3a) [inline socketio/src/client/raw_client.rs:343]: Please put comment above code

**Review by 1c3t3a — CHANGES_REQUESTED** [review]
The CI seems like a flake, lets work in your changes and hope the action is fixed by then.

File: engineio/src/packet.rs (hunk 5 above)
Comment (shenjackyuanjie) [reply engineio/src/packet.rs:1]: well……
I have to ask why is this line of code exist in the first place
╮( •́ω•̀ )╭

**Comment by shenjackyuanjie** [comment]
the code coverage still broke ╮(￣⊿￣)╭

**Comment by shenjackyuanjie** [comment]
@1c3t3a  I think you may need a fix for it

File: engineio/src/packet.rs (hunk 5 above)
Comment (1c3t3a) [reply engineio/src/packet.rs:1]: You opened a PR with the title "Fix the implementation for the multi payload". TBH I don't understand why this is necessary for the patch. I like to have clean commits, that do what the title says. If you submit a PR for "applying clippy lints", this would be appropriate. I am still accepting this change, but be aware that in bigger projects, people like clean PRs and no chaos.

**Review by 1c3t3a — APPROVED** [review]

**Comment by 1c3t3a** [comment]
> @1c3t3a I think you may need a fix for it

Oke, it doesn't matter for now, we can fix this separately. Thanks for the PR!
